//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSCliente.WSAlumnos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WSCliente.WSAlumnos.Alumno))]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alumno", Namespace="http://schemas.datacontract.org/2004/07/WCFServicio")]
    [System.SerializableAttribute()]
    public partial class Alumno : WSCliente.WSAlumnos.Respuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido_MaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido_PaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumCtrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_Materno {
            get {
                return this.Apellido_MaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_MaternoField, value) != true)) {
                    this.Apellido_MaternoField = value;
                    this.RaisePropertyChanged("Apellido_Materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_Paterno {
            get {
                return this.Apellido_PaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_PaternoField, value) != true)) {
                    this.Apellido_PaternoField = value;
                    this.RaisePropertyChanged("Apellido_Paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Carrera {
            get {
                return this.CarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CarreraField, value) != true)) {
                    this.CarreraField = value;
                    this.RaisePropertyChanged("Carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumCtrl {
            get {
                return this.NumCtrlField;
            }
            set {
                if ((object.ReferenceEquals(this.NumCtrlField, value) != true)) {
                    this.NumCtrlField = value;
                    this.RaisePropertyChanged("NumCtrl");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSAlumnos.WSAlumnos")]
    public interface WSAlumnos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSAlumnos/ObtenerAlumno", ReplyAction="http://tempuri.org/WSAlumnos/ObtenerAlumnoResponse")]
        WSCliente.WSAlumnos.Alumno ObtenerAlumno(string identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSAlumnos/ObtenerAlumno", ReplyAction="http://tempuri.org/WSAlumnos/ObtenerAlumnoResponse")]
        System.Threading.Tasks.Task<WSCliente.WSAlumnos.Alumno> ObtenerAlumnoAsync(string identificacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSAlumnosChannel : WSCliente.WSAlumnos.WSAlumnos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAlumnosClient : System.ServiceModel.ClientBase<WSCliente.WSAlumnos.WSAlumnos>, WSCliente.WSAlumnos.WSAlumnos {
        
        public WSAlumnosClient() {
        }
        
        public WSAlumnosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAlumnosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAlumnosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAlumnosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WSCliente.WSAlumnos.Alumno ObtenerAlumno(string identificacion) {
            return base.Channel.ObtenerAlumno(identificacion);
        }
        
        public System.Threading.Tasks.Task<WSCliente.WSAlumnos.Alumno> ObtenerAlumnoAsync(string identificacion) {
            return base.Channel.ObtenerAlumnoAsync(identificacion);
        }
    }
}
